[project]
name = "jsx"
version = "0.6.5"
authors = [
  { name="Xpo Development", email="dev@xpo.dev" },
]
description = "This package is deprecated. Please use the `python-seamless` package instead."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]

[project.urls]
Homepage = "https://github.com/xpodev/seamless"
Issues = "https://github.com/xpodev/seamless/issues"

[tool.setuptools.packages.find]
include = ["jsx*"]
exclude = ["tests*"]


[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
